### ISSUE TITLE
Download twilio record in my dataBase

### ISSUE THREAD

**Issue by asmabelhadj123** [eric-brechemier/how-i-replaced-skype-with-twilio#10]
Hii; I used the "action" option of twiML to send the recording of a call to my application and add the url and the text of call in my database 

but it doesn't  work

`<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial record="true"  >
      +######## 
  </Dial>
  <Record
          method="POST"
          action="http://myapp.com/phone_call/speech.php"  
          timeout="10"
   />
</Response>`

**Comment by eric-brechemier** [comment]
Hi @asmabelhadj123!

I am sorry, but your issue does not seem to be related to this guide. Here, I am not trying to record whole calls, only voicemails.

However, from my reading of [Twilio Voice documentation](https://www.twilio.com/docs/voice/twiml/dial#record), you don't need to use the `<Record>`element here, but to configure a callback in the [recordingStatusCallback](https://www.twilio.com/docs/voice/twiml/dial#recordingstatuscallback) attribute of the `<Dial>`element.

You can take a look at the example [Set Dual-Channel Recording on `<Dial>`](https://www.twilio.com/docs/voice/twiml/dial?code-sample=code-set-dual-channel-recording-on-dial-5&code-language=Node.js&code-sdk-version=3.x) for inspiration:

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial record="record-from-ringing-dual"
          recordingStatusCallback="www.myexample.com">
        <Number>+15558675310</Number>
    </Dial>
</Response>
```
