### ISSUE TITLE
Configure Twilio to send/receive text messages

### ISSUE THREAD

**Issue by eric-brechemier** [eric-brechemier/how-i-replaced-skype-with-twilio#7]
Ideally, I would like to:
* receive text messages sent to the Twilio number as SIP messages in the software phone
* forward SIP messages sent from the software phone as text messages

Barring that, I would like to:
* forward text messages received on the Twilio number as email messages
* forward replies to these email messages as text messages to the original sender

**Comment by HengYeDev** [comment]
I'm currently writing an app (fork linphone) that will receive SMS from the Twilio API and also do the features of Linphone.

**Comment by eric-brechemier** [comment]
@HengYeDev Thank you for letting me know. I'll be interested to test it. Which platform are you targeting?

**Comment by HengYeDev** [comment]
I'm targeting android for now, may also do linux, ubuntu touch, and sailfish

**Comment by eric-brechemier** [comment]
@HengYeDev It seems that you are only targeting mobile phones. I might not be able to test it then.

I am still interested to hear about how it pans out.

**Comment by HengYeDev** [comment]
I'm also trying to get it to forward to email and when you respond to the email you respond to the text. 


Heng Ye
https://yeheng.org | Twitter https://twitter.com/HengYeDev







---- On Mon, 18 Jan 2021 13:32:45 -0500 Eric Bréchemier <notifications@github.com> wrote ----




https://github.com/HengYeDev It seems that you are only targeting mobile phones. I might not be able to test it then.

I am still interested to hear about how it pans out.

**Comment by eric-brechemier** [comment]
Neat!

**Comment by eric-brechemier** [comment]
I have [compared different services to help me send and receive SMS messages by email](https://github.com/eric-brechemier/how-i-replaced-skype-with-twilio/issues/12); I have identified [Pipedream](https://pipedream.com) as a suitable solution, which supports:

* incoming email messages, to a custom address of the form `[unique-id]@upload.pipedream.net`
* incoming HTTP requests from webhooks, at a URL of the form `https://[unique-id].m.pipedream.net`
* email notifications from `notifications@pipedream.com` to the email used to register the pipedream account
* sending SMS through Twilio API, using a *standard* API key with limited privileges for authentication

The icing on the cake is that Pipedream allows to build workflows step by step, showing you how the incoming data look like at each step, and letting you select values from that data in the configuration of each following step. This is the part that allows to actually build the bridge from SMS to email and back again, where other services that I studied only provide the pillars on each end.

**Comment by eric-brechemier** [comment]
## Create Pipedream Account

**Note:** *There is a limitation in email notifications sent by Pipedream at the moment: they can only be sent to the email address that you used to sign up to the service. This limitation will be lifted in an upcoming update of the platform, but at the moment, you should sign up with the email address were you want to receive your SMS messages.*

1. Go to [Pipedream](https://pipedream.com/) home page
2. Click the button to <span><img align="top" width="90" alt="Signup For Free" src="https://user-images.githubusercontent.com/151276/160296265-df8dc2f8-5adc-481d-a6e8-94518fdc248f.png"></span>.
3. Fill in your email address (where you want to receive SMS messages) and your unique password for the service.

<p align="center">
  <kbd>
    <img width="400" alt="Sign Up Form" src="https://user-images.githubusercontent.com/151276/160296450-8c34318c-d170-4eb6-8eb7-bf6d6c9c9778.png">
  </kbd>
</p>
 
4. Click the <span><img align="top" width="60" alt="Sign Up" src="https://user-images.githubusercontent.com/151276/160296550-daedda97-bf3e-420c-b09e-295a52356d30.png"></span> button.
5. Confirm or modify your user name. By default, it is identical to the part of you email before the `@`sign, but only alphanumerical characters and dashes are allowed.

<p align="center">
  <kbd>
    <img width="400" alt="Confirm Username Form" src="https://user-images.githubusercontent.com/151276/160296710-b542ddcd-b779-44b7-9741-59b0d72d699c.png">
  </kbd>
</p>

6. You are invited to share more details about yourself.

<p align="center">
  <kbd>
    <img width="400" alt="Form to Tell Us More About Yourself" src="https://user-images.githubusercontent.com/151276/160297188-ffdbb87f-7ff1-49d9-9112-70b1cfbb495e.png">
  </kbd>
</p>

7. You can safely <span><img align="top" width="120" alt="Skip and continue" src="https://user-images.githubusercontent.com/151276/160297226-3c86b610-ef39-4bd8-814a-433cbde2468e.png"></span>.

This completes your sign up and initiates the creation of your first workflow.
We will start by configuring a workflow to send SMS messages by email.

But first, you can check your email and confirm your email address. You should receive an email of the form:

```
Thanks for signing up to Pipedream!

Please verify your email by clicking this link: https://api.pipedream.com/verify-email?token=[long-secret-token]
```

8. Click the link to confirm that your email address is valid.

Strange enough, no confirmation gets displayed.

**Comment by eric-brechemier** [comment]
## Configure Workflow to Send SMS by Email

This workflow is made of two steps:
1. a trigger: an email sent from your usual email client, which will provide the text and recipient for the SMS.
2. a connection to Twilio SMS API to send the text as an SMS to the destination number.

The wizard for the creation of a new workflow invites you to select the trigger:

<p align="center">
  <kbd>
    <img width="400" alt="New Workflow: Add Trigger" src="https://user-images.githubusercontent.com/151276/160299245-c6b16c37-edc6-4987-8c90-7defd6712c58.png">
  </kbd>
</p>

We'll start by naming our workflow. At the top left of the window, it is currently named **Untitled workflow**.

1. Click that name, select all text and replace it with your own name, e.g. **Send SMS by Email**.
2. Leave the field by clicking somewhere else or pressing the tab key. The new name is saved automatically.

<p align="center">
  <kbd>
    <img width="200" alt="Rename Workflow: Send SMS by Email" src="https://user-images.githubusercontent.com/151276/160299366-6b1ab0d2-04c1-4d85-8794-cee24ae731fc.png">
  </kbd>
</p>

3. The trigger that we want is called **Email**. There is no need to search for it, it is already present in the list on the right:

<p align="center">
  <kbd>
    <img width="400" alt="Select Email Trigger" src="https://user-images.githubusercontent.com/151276/160299444-d1b74c18-43e5-41ed-9d10-83280a552448.png">
  </kbd>
</p>

4. Click the **Email** trigger. A unique email address is generated as input for this workflow:

<p align="center">
  <kbd>
    <img width="400" alt="New Inbound Email" src="https://user-images.githubusercontent.com/151276/160299588-c514fe5c-df1d-44c2-823f-e5241373d1e2.png">
  </kbd>
</p>

5. The wizard is now waiting for you to send a realistic email to this inbound address. <span><img align="top" width="90" alt="Copy Email" src="https://user-images.githubusercontent.com/151276/160299638-63727323-106f-4f4a-af7f-1c12931e954d.png"></span> then open your usual email client.
6. You may want to create a contact for this email. You can include *Pipedream* and your Twilio phone number in the display name for this new contact, as a reminder that this is the email to send SMS messages from this phone number.

The text of the SMS will simply be the text of the email. To make things simpler at a later step, I have configured my email client to send these email messages as plain text rather than in HTML format, and to avoid including any signatures or inlining the original message in a reply.

The phone number of the recipient will be provided in international format, starting with a + and the country code, omitting any part of the number, such as a `0`, that is only used when calling local numbers. You should choose a regular mobile phone number to test the reception of SMS messages.

Your test email should contain something along these lines:
* **From:** your usual email address
* **To:** the Pipedream inbound email address which triggers your workflow (the one you just copied)
* **Subject:** *New SMS to +## ###-###-#####* (your regular mobile phone number, recipient of the test)
* **Body:** *Hey! This is my first SMS sent from my Twilio mobile phone number!*

7. When you are ready, send your test email. You are not going to get an SMS right away, because we are going to guide it step by step through the Pipedream workflow. The Pipedream interface should now show that your new event just arrived:

<p align="center">
  <kbd>
    <img width="400" alt="Email Trigger Received a New Event" src="https://user-images.githubusercontent.com/151276/160300693-d71b6e79-57c2-47f1-8d56-1d0c28c270e3.png">
  </kbd>
</p>

8. Click the new event. It displays the title of your email:

<p align="center">
  <kbd>
    <img width="400" alt="New Email Event" src="https://user-images.githubusercontent.com/151276/160301633-b4963393-abe0-4a1e-ace4-3d7ede3bd737.png">
  </kbd>
</p>

9. Click this title and the event gets parsed as a hierarchical data structure.

<p align="center">
  <kbd>
    <img width="400" alt="Email Event Tree Structure" src="https://user-images.githubusercontent.com/151276/160301801-7f06bbcc-d3c8-4d23-a68e-1bd5155a5f01.png">
  </kbd>
</p>

10. You can click on the elements of that tree structure to expand them and find the parts of interest:

* the sender, **From**: `steps.trigger.event.headers.from.text`
* the recipient, **To**: `steps.trigger.event.headers.to.text`
* the subject of the email: `steps.trigger.event.headers.subject`
* the text of the email: `steps.trigger.event.body.text`

11. That's all we need. Let's <span><img align="top" width="70" alt="Continue" src="https://user-images.githubusercontent.com/151276/160301985-2e953ac0-0346-4395-bc16-728c2725b074.png"></span>.

12. A second step is added, in which we will select the action to do in response to the trigger:

<p align="center">
  <kbd>
    <img width="400" alt="Add a Step" src="https://user-images.githubusercontent.com/151276/160302082-e86cd1b0-d549-4c12-bcd4-e6553269ef9f.png">
  </kbd>
</p>

13. In the input field to *Search for an app*, type **Twilio**, then select the Twilio app in the results:

<p align="center">
  <kbd>
    <img width="400" alt="Search and Select Twilio App" src="https://user-images.githubusercontent.com/151276/160302142-4a414726-5066-4ddf-8e5f-cceebe2f356f.png">
  </kbd>
</p>

14. In the list of actions part of the Twilio app, select **Send SMS**:

<p align="center">
  <kbd>
    <img width="400" alt="Select Send SMS Action" src="https://user-images.githubusercontent.com/151276/160302236-a7eed02e-449c-4593-9527-b7b946bd8173.png">
  </kbd>
</p>

15. You are now invited to connect your Twilio account:

<p align="center">
  <kbd>
    <img width="400" alt="Settings for Send SMS Action" src="https://user-images.githubusercontent.com/151276/160302273-3100db2e-b286-44c3-b189-cb7fff34bc85.png">
  </kbd>
</p>

16. Click <span><img align="top" width="160" alt="connect-a-twilio-account" src="https://user-images.githubusercontent.com/151276/160302306-7f54d857-a703-45b7-ab31-ec510508dd52.png"></span>.

17. The connection to Twilio API requires 3 different things, which you will find or create in your Twilio account:

* an **SID** and **Secret**, which you will get by creating a *Standard API Key*.
*  an **Account SID**, which you will find on one of the main home pages of your dashboard.

<p align="center">
  <kbd>
    <img width="400" alt="Create a New Connection to Twilio" src="https://user-images.githubusercontent.com/151276/160302512-be0fab1f-c393-4c5a-b881-8296e74ef9ca.png">
  </kbd>
</p>

18. Sign in to Twilio and go to your console dashboard.

19. Scroll down the page and you will find your **Account SID** in the **Account Info** section.<br>Copy it and paste it to the **AccountSid** field of the Pipedream configuration form.

<p align="center">
  <kbd>
    <img width="400" alt="Copy Account SID from Twilio" src="https://user-images.githubusercontent.com/151276/160302671-626171fc-7ef0-4bce-ab4e-d70115de44df.png">
  </kbd>
</p>

Instead of providing your master token, which is like giving the password to your whole Twilio account, we are going to create an API key with more limited privileges.

20. Open the <span><img align="top" width="60" alt="Account" src="https://user-images.githubusercontent.com/151276/160302768-e7bf6a1b-f227-40eb-9f26-d672623c3ff2.png"> Menu found in the top right of your Twilio dashboard, then select <span><img align="top" width="120" alt="API keys & tokens" src="https://user-images.githubusercontent.com/151276/160302838-669eab23-ba27-4a80-9a57-30da36f3e893.png"></span> under the **Keys & Credentials section**.
21. You may be requested to provide a confirmation code to access this sensitive area. In my case, the verification code was sent to my email.

<p align="center">
  <kbd>
    <img width="400" alt="Verification Code Required for Access" src="https://user-images.githubusercontent.com/151276/160302997-c0bace8d-3433-4813-95b6-6425676c3395.png">
  </kbd>
</p>

22. Provide the code and <span><img align="top" width="50" alt="Verify" src="https://user-images.githubusercontent.com/151276/160303048-d13b6930-a11e-4a56-b1fe-5b577633f47c.png"></span>.
23. You probably don't have any API keys yet:

<p align="center">
  <kbd>
    <img width="400" alt="You don't have any API keys" src="https://user-images.githubusercontent.com/151276/160303163-5aaa7128-6c19-408a-83e3-26b2348679c0.png">
  </kbd>
</p>

24. Click the button to <span><img align="top" width="100" alt="Create API Key" src="https://user-images.githubusercontent.com/151276/160303207-a1aa02f7-cf7e-4da4-80d2-0ad4c6696ab9.png"></span>.
25. Describe the key as **Pipedream (Send SMS)**:

<p align="center">
  <kbd>
    <img width="400" alt="Create New API Key" src="https://user-images.githubusercontent.com/151276/160303370-d61b1cbc-78e4-4753-80f4-15b0491f201b.png">
  </kbd>
</p>

26. Click <span><img align="top" width="90" alt="Create API Key" src="https://user-images.githubusercontent.com/151276/160303395-513f2c6d-4f42-454f-a20e-177cd531bd4a.png"></span> button to create a new Standard API key.
27. A notification pops out briefly to confirm the creation of the key. The generated **SID** and **Secret** are now displayed below the three fields which describe the key:

<p align="center">
  <kbd>
    <img width="400" alt="Copy Secret Key" src="https://user-images.githubusercontent.com/151276/160303572-722cec78-6b60-4aba-9d6c-5998a132c64b.png">
  </kbd>
</p>

28. Copy the **SID** and **Secret** in turn to the corresponding fields in the Pipedream connection settings.
29. Optionally, describe this connection as **Twilio API**:

<p align="center">
  <kbd>
    <img width="400" alt="Create a New Connection to Twilio API" src="https://user-images.githubusercontent.com/151276/160303781-09989578-1b81-465e-918d-08f2bd29e5dc.png">
  </kbd>
</p>

31. Then <span><img align="top" width="40" alt="Save" src="https://user-images.githubusercontent.com/151276/160303676-4a907887-4825-4bad-a5ad-b47d289b6172.png"></span>.

**Note:** *If your connection to the Twilio API fails to authenticate, you may have created the API key for a different region.<br>That happened to me: I had mistakenly created the API key for the Ireland region instead of the US.*

32. Next, click <span><img align="top" width="200" alt="Select an option or enter a custom expression…" src="https://user-images.githubusercontent.com/151276/160303871-c731fa4b-63f6-4343-a6a5-a842ddb013aa.png"></span> in the **From** field.
33. Wait while the Twilio API is contacted to list your phone numbers, then click on your Twilio phone number in the list of results:

<p align="center">
  <kbd>
    <img width="400" alt="Select Twilio Phone Number" src="https://user-images.githubusercontent.com/151276/160303990-fa0a53d4-7a99-4309-8ebd-dc4771d4db6f.png">
  </kbd>
</p>

We will use an expression to extract the phone number of the recipient from the subject of the email. Remember that we formatted the subject with the phone number in international format at the end: *New SMS to +## ###-###-#####*. We identified previously that the subject is stored at the location `steps.trigger.event.headers.subject` in the event generated for the incoming email by Pipedream. We are going to use a regular expression to extract the phone number, starting with the `+` sign, and keeping only the digits, discarding all other symbols such as dashes added for readability.

I used [RegExr](https://regexr.com/) to test different regular expressions. I designed the replacement in two steps to cover some edge cases. The phone number is expected to start with the last `+` sign in the subject. Everything before the last `+` sign will be discarded:

1. Remove all characters before the `+` sign found closest to the end: `.replace(/^.+\+/,'+')`
2. Keep only the `+` sign and digits, discarding all separators and other symbols: `.replace(/[^+0-9]/g,'')`

Then I tested these replacements in the JavaScript console of a browser:

```
"New SMS to +1202-555-0488".replace(/^.+\+/,'+').replace(/[^+0-9]/g,'')
"+12025550488"

"Re[3]: 3rd SMS +1-2-3 to +1202-555-0488".replace(/^.+\+/,'+').replace(/[^+0-9]/g,'')
"+12025550488"
```

34. Copy and paste the following expression in the **To** field of the `send_sms` configuration:

```
{{steps.trigger.event.headers.subject.replace(/^.+\+/,'+').replace(/[^+0-9]/g,'')}}
```

35. For the text of the SMS, we will simply copy the contents of the email. Copy the following expression in the **Message Body** field of the `send_sms` configuration:

```
{{steps.trigger.event.body.text}}
```

<p align="center">
  <kbd>
    <img width="400" alt="send_sms Configuration Complete" src="https://user-images.githubusercontent.com/151276/160305238-bdfb4541-8d00-45c3-b36e-bee644822ec4.png">
  </kbd>
</p>

36. The configuration of the workflow to send SMS messages by Email is now complete, and your test SMS is ready to leave.

37. If your test number is in a different country than your Twilio phone number or if you plan to send SMS messages internationally, you should activate the [geographic permissions](https://support.twilio.com/hc/en-us/articles/223181108-How-International-SMS-Permissions-work) for each of these countries. In the **Messaging** section of the Twilio dashboard, open the **Settings** and **Geo permissions** subsections. Then select each country or region that you want to allow to send and receive SMS messages from.

<p align="center">
  <kbd>
    <img width="400" alt="Twilio Messaging Geographic Permissions" src="https://user-images.githubusercontent.com/151276/160463833-9876ce3c-9db3-4adc-abe2-18364a112cb3.png">
  </kbd>
</p>

38. You can click <span><img align="top" width="45" alt="Test" src="https://user-images.githubusercontent.com/151276/160305270-a602357f-e7db-44b3-aea8-cc562130b0c8.png"></span> button to send your SMS message. If all goes well, you should see a notification that the test is in progress for a little while, then a notification of success.

<p align="center">
  <kbd>
    <img width="400" alt="Test Complete: Success" src="https://user-images.githubusercontent.com/151276/160461577-ac0113f6-3b5a-41a1-9221-5eab0e71ced0.png">
  </kbd>
</p>

39. The `send_sms`step now shows the successful result.

<p align="center">
  <kbd>
    <img width="400" alt="send_sms Successul" src="https://user-images.githubusercontent.com/151276/160305691-ecef887b-135b-42d4-8ada-798a70ba8a3c.png">
  </kbd>
</p>

40. The SMS itself may take a while to arrive. In the meantime, you can check the logs on Twilio's side in the **Monitor** section of your dashboard, opening the **Logs** and **Messaging** subsections to see more details about the delivery of that SMS.

41. Once you have successfully received the SMS, you can now <span><img align="top" width="50" alt="Deploy" src="https://user-images.githubusercontent.com/151276/160305729-bf9bd183-201f-4045-9521-b1dc4ab9f1f5.png"></span> the Pipedream workflow to allow it to process events automatically, instead of reviewing them step by step.

<p align="center">
  <kbd>
    <img width="200" alt="Congrats" src="https://user-images.githubusercontent.com/151276/160305777-aef1064e-c8d0-43e4-b6c0-ff080609ffce.png">
  </kbd>
</p>

**Note:** *When sending an SMS to a phone number in a different country, [your Twilio phone number may not be displayed as the sender](https://support.twilio.com/hc/en-us/articles/223181088-Why-do-some-SMS-recipients-see-a-Sender-ID-that-is-not-my-Twilio-number-). The recipient may see the short code of a local service instead. This should not happen when sending messages within the same country as your Twilio phone number.*

**Comment by eric-brechemier** [comment]
## Configure Workflow to Receive SMS by Email

We are now going to configure a second workflow to receive SMS messages as emails. Again, this workflow will have two steps:

1. a trigger step, an HTTP webhook configured in Twilio to get notified of new SMS messages.
2. an action step to send ourselves an email with the contents of the SMS.

This second workflow does not require a connection to Twilio API. It listens on an HTTP URL, which we will configure to get triggered by new SMS messages in the Twilio dashboard.

1. In the left sidebar of your Pipedream dashboard, click <span><img align="top" width="90" alt="Workflows" src="https://user-images.githubusercontent.com/151276/161102746-d9218a80-a5a6-4a5a-bb22-719da25d68f9.png"></span> to open the list of workflows.

2. Click the <span><img align="top" width="65" alt="New" src="https://user-images.githubusercontent.com/151276/161103069-1a2132a1-2bf3-44be-a113-48dcd1385120.png"></span> button to create a new workflow. We have now reached the stage where we were at the beginning of the configuration of the first workflow, which was created automatically for us just after the signup.

<p align="center">
  <kbd>
    <img width="400" alt="New Workflow" src="https://user-images.githubusercontent.com/151276/161103922-60a1ab7d-c3ca-4fe8-ac92-404ac25075ac.png">
  </kbd>
</p>

3. Let's rename our workflow. Click the current name, *Untitled workflow* then remove previous text and type the new name, e.g. *Receive SMS by Email*. The name is saved automatically when you leave the input field.

<p align="center">
  <kbd>
    <img width="200" alt="Receive SMS by Email" src="https://user-images.githubusercontent.com/151276/161104439-c8b69e40-a500-4b3f-bcf9-3ea9d8eaae70.png">
  </kbd>
</p>

4. The trigger that we need is already displayed at the top of the list on the right.
 
<p align="center">
  <kbd>
    <img align="top" width="400" alt="Select HTTP/Webhook Requests" src="https://user-images.githubusercontent.com/151276/161104751-5f8e2473-feb2-4de6-b05e-3a64d3df98ee.png">
  </kbd>
</p>

5. Click **HTTP / Webhook Requests** to select this first step as trigger.

<p align="center">
  <kbd>
    <img width="400" alt="New HTTP/Webhook Trigger" src="https://user-images.githubusercontent.com/151276/161105227-bef5592f-c9bb-48f9-b33a-1ea9764ef8e1.png">
  </kbd>
</p>

6. Twilio is expecting an answer from our webhook, a list of instructions in Twilio Markup Language (TwiML) format, a dialect of the XML language. We have no further actions to request from Twilio, so we will send an empty response, which has the following structure:

```
<?xml version="1.0" encoding="UTF-8" ?>
<Response/>
```

and must be served with the HTTP `Content-Type` header `application/xml`.

7. Under *HTTP Response*, click the default value **Return HTTP 200 OK** to open the list and select **Return a static response** instead.

<p align="center">
  <kbd>
    <img width="400" alt="HTTP Response: Return a static response" src="https://user-images.githubusercontent.com/151276/161107594-bc42557d-5f07-43ff-9ac7-2dffbe2e7345.png">
  </kbd>
</p>

8. Under *Status Code*, type **200**:

<p align="center">
  <kbd>
    <img width="400" alt="Status Code: 200" src="https://user-images.githubusercontent.com/151276/161107851-8e194abc-5013-426a-ade1-87ec798f42c0.png">
  </kbd>
</p>

9. Under *Headers*, click the *EMPTY:EMPTY* placeholder and replace it with **Content-Type: application/xml**:

<p align="center">
  <kbd>
    <img width="400" alt="EMPTY:EMPTY header placeholder" src="https://user-images.githubusercontent.com/151276/161108258-e3bcfc1d-f766-4e1a-b51d-81679d484741.png">
  </kbd>
</p>

<p align="center">
  <kbd>
    <img width="400" alt="Content-Type: application/xml" src="https://user-images.githubusercontent.com/151276/161108630-d313b26c-8ec3-46e1-836d-e081ee97c513.png">
  </kbd>
</p>

10. Click the <span><img align="top" width="30" alt="X" src="https://user-images.githubusercontent.com/151276/161109078-cdf22f19-9cec-46f7-b3e2-b868c242f4a4.png"></span> button to close that part of the form.

11. Under the **Body**, click the input field and copy/paste there our static TwiML response:

```
<?xml version="1.0" encoding="UTF-8" ?>
<Response/>
```

<p align="center">
  <kbd>
    <img width="400" alt="Static TwiML response" src="https://user-images.githubusercontent.com/151276/161109631-3999ed06-daa6-4aa8-bbfc-c2d4e8953e8e.png">
  </kbd>
</p>

12. Finally, click <span><img align="top" width="110" alt="Save and continue" src="https://user-images.githubusercontent.com/151276/161109930-15951210-c8c4-4b3d-af34-469e07bcc71b.png"></span> button to save our trigger step.

13. Once the trigger is saved, Pipedream generates a new URL of the form **https://[unique-id].m.pipedream.net** for this trigger:

<p align="center">
  <kbd>
    <img width="400" alt="New Webhook URL" src="https://user-images.githubusercontent.com/151276/161110396-d77dc3a2-40d8-4de9-98cd-f4c10fcc4718.png">
  </kbd>
</p>

14. Click <span><img align="top" width="90" alt="Copy URL" src="https://user-images.githubusercontent.com/151276/161110777-58e5ea30-c0b5-4710-a7f1-85cb0a302546.png"></span> to copy this URL. We will configure it as webhook for new SMS messages in the Twilio dashboard.

15. Go to your Twilio dashboard. In the *Develop* sidebar, open the **Phone Numbers** section then the **Manage** and **Active Numbers** subsections.

16. Click the link which displays your phone number in the list displayed on the right.

17. In the **Messaging** section, select *Webhook* and copy the URL of your Pipedream trigger under *WHEN A MESSAGE COMES IN*:

<p align="center">
  <kbd>
    <img width="400" alt="Twilio Messaging Webhook: When a Message Comes In" src="https://user-images.githubusercontent.com/151276/161111852-f1581ca2-4fd6-427d-8103-f88e80d2a623.png">
  </kbd>
</p>

18. Click the <span><img align="top" width="45" alt="Save" src="https://user-images.githubusercontent.com/151276/161112187-e08aa657-bfce-4f18-9393-8e26aa9c43fe.png"></span> button to save the webhook configuration.

19. Send an SMS to your Twilio phone number using a regular mobile phone. This is going to feed the Pipedream webhook which will show us what kind of data to expect from Twilio.

20. If all goes well, the Pipedream trigger shows that a new event has arrived:

<p align="center">
  <kbd>
    <img width="400" alt="New SMS event" src="https://user-images.githubusercontent.com/151276/161115361-00fb5204-e0ef-4e3e-a032-8487caf74117.png">
  </kbd>
</p>

21. Click <span><img align="top" width="90" alt="Select event…" src="https://user-images.githubusercontent.com/151276/161115592-5b261029-78c6-4092-aea7-40e6af1e1158.png"></span> to open the list and select the new event in the list:

<p align="center">
  <kbd>
    <img width="400" alt="Select New SMS Event" src="https://user-images.githubusercontent.com/151276/161115838-93003c39-90da-4450-92b3-f25b006f6f03.png">
  </kbd>
</p>

22. Pipedream displays the data received from Twilio as a hierarchical structure:

<p align="center">
  <kbd>
    <img width="400" alt="Test SMS Data" src="https://user-images.githubusercontent.com/151276/161116487-9bc492de-0875-4a95-8f2b-09cc4ac43fad.png">
  </kbd>
</p>

23. You can click elements in that tree to expand them and identify the location of items of interest. I have found the path of the two parts of the SMS that we will include in email notifications to yourself:

* the sender's phone **From** number, in international format: `steps.trigger.event.body.From`
* the **Text** of the message: `steps.trigger.event.body.Body`

24. Click the <span><img align="top" width="80" alt="Continue" src="https://user-images.githubusercontent.com/151276/161117496-8236bf77-7b07-433f-bf98-fcc702e53de2.png"></span> button to complete the configuration of the webhook trigger.

25. We will now add the **Send Email** action step, which is available in the list displayed on the right:

<p align="center">
  <kbd>
    <img width="400" alt="Select action to Send an Email to Yourself" src="https://user-images.githubusercontent.com/151276/161117891-5a25e15e-916a-4207-bc68-2d4530c5de15.png">
  </kbd>
</p>

26. The configuration of the **Send Email** action step starts:

<p align="center">
  <kbd>
    <img width="400" alt="email_me action setup" src="https://user-images.githubusercontent.com/151276/161118623-df169187-4ba5-42f2-8f0b-fb26c8bb626c.png">
  </kbd>
</p>

In the subject, we will include the phone number of the sender, using a template message of the form:

```
New SMS from {{steps.trigger.event.body.From}}
```

27. Under *Subject*, copy the above template, which you can customize to your liking:

<p align="center">
  <kbd>
    <img width="400" alt="Email Subject Template" src="https://user-images.githubusercontent.com/151276/161118915-2aa72a4d-f348-4ef2-bcf1-77d389f24049.png">
  </kbd>
</p>

28. Click the <span><img align="top" width="30" alt="X" src="https://user-images.githubusercontent.com/151276/161109078-cdf22f19-9cec-46f7-b3e2-b868c242f4a4.png"></span> button to close that part of the form.

For the text of the email, we will simply provide the text of the SMS, using the template below:

```
{{steps.trigger.event.body.Body}}
```

29. Under *Text*, copy the above template:

<p align="center">
  <kbd>
    <img width="400" alt="Email Text Template" src="https://user-images.githubusercontent.com/151276/161119826-a003917b-10eb-4ae8-b4fc-85269f56bfda.png">
  </kbd>
</p>

30. Click the <span><img align="top" width="30" alt="X" src="https://user-images.githubusercontent.com/151276/161109078-cdf22f19-9cec-46f7-b3e2-b868c242f4a4.png"></span> button to close that part of the form.

31. Click the <span><span><img align="top" width="45" alt="Test" src="https://user-images.githubusercontent.com/151276/160305270-a602357f-e7db-44b3-aea8-cc562130b0c8.png"></span> button to receive your test SMS by email. 

32. A few seconds later, Pipedream should display that the email was sent successfully:

<p align="center">
  <kbd>
    <img width="400" alt="email_me Action Successful" src="https://user-images.githubusercontent.com/151276/161120986-31985866-ddcd-43d0-8b43-a464703e901a.png">
  </kbd>
</p>

33. You should now have received an email from `notifications@pipedream.com` on the email address that you used to register your Pipedream account.

34. Once you have successfully received the email message, you can <span><img align="top" width="50" alt="Deploy" src="https://user-images.githubusercontent.com/151276/160305729-bf9bd183-201f-4045-9521-b1dc4ab9f1f5.png"></span> your second Pipedream workflow.

<p align="center">
  <kbd>
    <img width="200" alt="Congrats" src="https://user-images.githubusercontent.com/151276/160305777-aef1064e-c8d0-43e4-b6c0-ff080609ffce.png">
  </kbd>
</p>
 
**Note:** *If you have not validated your email address, you may not receive any email, although testing the workflow will still pretend that the email was sent successfully.*

**Comment by eric-brechemier** [comment]
You may leave your comments below.

**Comment by ally9335** [comment]
@eric-brechemier you have a French number which is capable of receiving SMS, right? When searched for a French number at "buy a number", there's no support for  SMS in France at all. How can it be?



![Screenshot_20230903_232241](https://github.com/eric-brechemier/how-i-replaced-skype-with-twilio/assets/60418495/a18b79dc-cdbd-439a-852b-6e2a68bdbd9e)

**Comment by eric-brechemier** [comment]
@ally9335 Sorry for the late answer. I do have a French phone number with SMS support.

In my experience, the availability of Twilio Phone Numbers in different countries varies over time. If I remember correctly, I had to check a couple of days in a row to find a suitable phone number in the UK. There might be a shortage of French numbers at the moment.

Checking today, there is not a single French phone number available from Twilio:

<img width="1160" alt="no French phone number" src="https://github.com/eric-brechemier/how-i-replaced-skype-with-twilio/assets/151276/e71f23e5-0563-4e43-ad44-5868ae6f323c">
