### ISSUE TITLE
Calls are not encrypted

### ISSUE THREAD

**Issue by eric-brechemier** [eric-brechemier/how-i-replaced-skype-with-twilio#8]
Twilio does not currently support encryption of [calls registered with Twilio's endpoint](https://www.twilio.com/docs/voice/api/sip-making-calls#transport).
Encrypted transport is only supported with [SIP trunking](https://www.twilio.com/docs/sip-trunking):

> NOTE: Twilio does not support SRTP on SIP Interface.
> SRTP is supported on Elastic SIP Trunking.
> — https://www.twilio.com/docs/voice/api/sip-making-calls#transport

**Comment by AmIJesse** [comment]
Twilio does appear to support call encryption now, under the sip domain settings you can enable "Secure Media", and enable "SRTP" and "Mandatory Encryption" under linphone's "Calls abd Chat" settings.

**Comment by eric-brechemier** [comment]
@AmIJesse Thank you for the heads-up. I'll try it out.

**Comment by eric-brechemier** [comment]
> # Secure Media
>
> Secure Media uses encryption to ensure that the call media and associated signaling remains private during transmission. Transport Layer Security (TLS) provides encryption for SIP signaling. Secure Real-time Transport Protocol (SRTP) provides encryption for call content/media packets.
>
> SRTP provides a framework for the encryption of RTP & RTCP. [RFC 4568](https://tools.ietf.org/html/rfc4568), Session Description Protocol (SDP) Security Description (SDES) for Media Streams, defines such a protocol specifically designed to exchange cryptographic material using a newly defined SDP crypto attribute.
>
> ---
>
> ## Inbound:
>
> You can enable or disable Secure Media in your SIP Domain. It is disabled by default.
>
> You can expect the following:
>
> * **Enabled:** *TLS must be used to encrypt SIP messages and SRTP must be used for the media packets. Any non-encrypted calls will be rejected.*
> * **Disabled:** *RTP must be used for media packets. SIP messages may be sent in the clear or using TLS. Any SRTP encrypted calls will be rejected.*
>
> ### info
> * *SRTP supports the following crypyto suites: `AES_CM_128_HMAC_SHA1_80` and `AES_CM_128_HMAC_SHA1_32`. Both may be included in an order of preference.**
> * *The optional master key identifier (MKI) parameter is not supported**
>
> ---
>
> ## Outbound:
>
> Ensure you configure `secure=true` parameter as part of SIP URI to secure media in SIP outbound calls.
>
>     <?xml version="1.0" encoding="UTF-8"?>
>     <Response>
>       <Dial>
>         <Sip>sip:jack@example.com;secure=true</Sip>
>       </Dial>
>     </Response>
>
> The default port **5061** will be used for TLS.
>
> ### info
> * *Only a single crypto suite for SRTP will be included: `AES_CM_128_HMAC_SHA1_80`*
> * *The optional master key identifier (MKI) parameter is not supported*
>
> ---
>
> ## Importing Twilio's Root CA Certificate
>
> TLS is used to encrypt SIP signaling between SIP endpoints. In order for this to function properly, it is required that certain devices in your network import an SSL certificate. Twilio uses certificates from a CA (Certificate Authority). It is important that you add the following root certificate to your communications infrastructure to establish its authenticity on the network. [Download Twilio's CA certificate](https://www.twilio.com/resources/images/docs/cacert.pem).
>
> It is important to note that Twilio uses a wildcard certificate which can be used for multiple subdomains of a domain (`*.sip.twilio.com`). If your network element does not support wild carded certificates please disable certificate validation.
> (...)
> — https://www.twilio.com/docs/voice/api/secure-media

**Comment by eric-brechemier** [comment]
Also:

> ### Transport
>
> Set a parameter on your SIP URI to specify what transport protocol you want to use. Currently, this is limited to `UDP`, `TCP` and `TLS`. By default, Twilio sends your `SIP INVITE` over `UDP`. Change this by using the transport parameter:
>
>    <?xml version="1.0" encoding="UTF-8"?>
>    <Response>
>        <Dial>
>            <Sip>
>                sip:jack@example.com;transport=tcp
>            </Sip>
>        </Dial>
>    </Response>
>
> Alternatively, you may customize it to use TLS for SIP signaling. When using TLS, the default port will be 5061 however, a different one may be specified.
>
>    <?xml version="1.0" encoding="UTF-8"?>
>    <Response>
>        <Dial>
>            <Sip>
>                sip:jack@example.com;transport=tls
>            </Sip>
>        </Dial>
>    </Response>
>
> — https://www.twilio.com/docs/voice/twiml/sip#transport

**Comment by eric-brechemier** [comment]
I have updated the [corresponding section](https://github.com/eric-brechemier/how-i-replaced-skype-with-twilio/issues/5#issuecomment-488743605) of the step by step setup:

## Create a SIP Domain
(…)

10. Under **Secure Media**, click the <span><img align="top" width="80" alt="Disabled" src="https://user-images.githubusercontent.com/151276/57087276-fbe41580-6cff-11e9-9bf5-9c449636255b.png"></span> button to encrypt SIP registration and calls, deterring eavesdropping:

<p align="center">
  <kbd>
  <img width="400" alt="Secure Media Enabled" src="https://user-images.githubusercontent.com/151276/154802322-88431394-5aae-4b61-812c-114d191c83b1.png">
  </kbd>
</p>

**Comment by eric-brechemier** [comment]
I have also added [instructions to configure call encryption in Linphone](https://github.com/eric-brechemier/how-i-replaced-skype-with-twilio/issues/5#issuecomment-488824107). The option to send SIP registration over TLS was already selected.

## Connect to SIP from your Computer
(…)
1. Open Linphone > Preferences > Calls and Chat.

2. Under **Calls**, click the <span><img align="top" width="42" alt="SRTP" src="https://user-images.githubusercontent.com/151276/154804999-95ab1a71-dd26-4613-8ace-b8bbe92c5843.png"></span> button. I also chose to make encryption mandatory, just to make sure.

<p align="center">
  <kbd>
    <img width="400" alt="Call Encryption Settings in Linphone" src="https://user-images.githubusercontent.com/151276/154805117-725a9999-f836-4915-9ec7-b9ec378eb3e1.png">
  </kbd>
</p>

_Note: Twilio will neither accept unencrypted calls on a domain where encryption has been enabled, nor encrypted calls on a domain where it has not been enabled. Once encryption has been enabled for a SIP domain, you have to use it, otherwise all your calls will get rejected._

**Comment by eric-brechemier** [comment]
With these two changes, SIP registrations and calls are now expected to be encrypted.

**Comment by eric-brechemier** [comment]
Linphone shows outgoing calls as encrypted with SRTP:

<img width="189" alt="outgoing-call-encrypted" src="https://user-images.githubusercontent.com/151276/154806757-5644d47a-7d84-4cbf-88aa-75b92dd8b246.png">

**Comment by eric-brechemier** [comment]
As noted by [user _Eduardo_squidwardo_ on Reddit](https://www.reddit.com/r/VOIP/comments/hq34la/comment/gfs6pu7/), the *Encryption is mandatory* option must ***not*** be selected at this point.

Otherwise, incoming calls are rejected by Linphone, which answers:

```
SIP/2.0 488 Not acceptable here
```

after the SDP offer/answer process fails:

```
Doing SDP offer/answer process of type incoming
Declining mline 0, no corresponding stream in local capabilities description.
```

While when _Encryption is mandatory_ is disabled, the SDP offer/answer process succeeds with:

```
Doing SDP offer/answer process of type incoming
Found matching configurations: local configuration index 0 remote offered configuration index 0
```

**Comment by eric-brechemier** [comment]
Linphone shows that incoming calls are not encrypted:

<img width="102" alt="incoming-call-not-encrypted" src="https://user-images.githubusercontent.com/151276/154807163-3dae2f70-4213-4c7c-bdcd-c2f5305ad763.png">

**Comment by eric-brechemier** [comment]
I have disabled _Encryption is mandatory_ option for now, until I find how to encrypt incoming calls as well.

## Connect to SIP from your Computer
(…)

If you choose to make encryption mandatory, incoming calls will get rejected unless they are encrypted as well. **This option must not be checked at this point.**

<p align="center">
  <kbd>
    <img width="253" alt="Encryption is not mandatory" src="https://user-images.githubusercontent.com/151276/154807571-a98e4615-fb80-4b62-9359-fc625fe14600.png">
  </kbd>
</p>

**Comment by eric-brechemier** [comment]
This is the behavior described in the [Secure Media](https://www.twilio.com/docs/voice/api/secure-media) documentation.

The _Secure Media_ option of SIP domains applies to [inbound calls only](https://www.twilio.com/docs/voice/api/secure-media).
When enabled, SRTP encryption must be used by the Linphone client, or calls will get rejected.

For [outbound calls](https://www.twilio.com/docs/voice/api/secure-media), an extra parameter must be included in the `<Sip>` URL of the `<Dial>` verb in TwiML:

> Ensure you configure `secure=true` parameter as part of SIP URI to secure media in SIP outbound calls.
>
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Response>
>   <Dial>
>     <Sip>sip:jack@example.com;secure=true</Sip>
>   </Dial>
> </Response>
> ```

**Comment by eric-brechemier** [comment]
After this change in the TwiML Bin *Receiving Calls from Regular Phones to SIP*, incoming calls are now encrypted with SRTP as well:

<img width="189" alt="incoming-call-is-encrypted-with-srtp" src="https://user-images.githubusercontent.com/151276/154814241-1b746042-0eb0-4250-b798-4ae7eb18174f.png">

It becomes possible to make encryption mandatory, and incoming calls are no longer rejected, since they are encrypted:

<img width="250" alt="encryption-is-mandatory" src="https://user-images.githubusercontent.com/151276/154814287-0041e657-fd27-4df5-8688-1e43c4e5c1ab.png">

**Comment by eric-brechemier** [comment]
Two parameters must be set in the SIP URL:
* `transport=tls` to [encrypt the SIP INVITE](https://www.twilio.com/docs/voice/twiml/sip#transport),
* `secure=true` to [encrypt the incoming SIP call](https://www.twilio.com/docs/voice/api/secure-media#outbound).

**Comment by eric-brechemier** [comment]
Including both parameters in the URL leads the call to fail, when Linphone requires encryption, in the same as when no call encryption was applied:

```
2022-02-19 19:58:44:083 [linphone/liblinphone] MESSAGE Doing SDP offer/answer process of type incoming
2022-02-19 19:58:44:083 [linphone/liblinphone] MESSAGE Declining mline 0, no corresponding stream in local capabilities description.
```

and disabling this requirement, the incoming call is no longer encrypted.

It thus appears that usage of `secure=true`, described in the Secure Media documentation, is superseding the more limited `transport=tls` parameter described in the documentation of the TwiML `<Sip>` noun.

I'll use `secure=true` alone from this point.

**Comment by eric-brechemier** [comment]
Calls are now encrypted.

**Comment by eric-brechemier** [comment]
I combined SIP parameters with `&amp;` instead of `;`. Let's try again.

The format of SIP URLs is described in [RFC 2543](https://datatracker.ietf.org/doc/html/rfc2543):

```
  SIP-URL         = "sip:" [ userinfo "@" ] hostport
                    url-parameters [ headers ]
  userinfo        = user [ ":" password ]
  user            = *( unreserved | escaped
                  | "&" | "=" | "+" | "$" | "," )
  password        = *( unreserved | escaped
                  | "&" | "=" | "+" | "$" | "," )
  hostport        = host [ ":" port ]
  host            = hostname | IPv4address
  hostname        = *( domainlabel "." ) toplabel [ "." ]
  domainlabel     = alphanum | alphanum *( alphanum | "-" ) alphanum
  toplabel        = alpha | alpha *( alphanum | "-" ) alphanum
  IPv4address     = 1*digit "." 1*digit "." 1*digit "." 1*digit
  port            = *digit
  url-parameters  = *( ";" url-parameter )
  url-parameter   = transport-param | user-param | method-param
                  | ttl-param | maddr-param | other-param
  transport-param = "transport=" ( "udp" | "tcp" )
  ttl-param       = "ttl=" ttl
  ttl             = 1*3DIGIT       ; 0 to 255
  maddr-param     = "maddr=" host
  user-param      = "user=" ( "phone" | "ip" )
  method-param    = "method=" Method
  tag-param       = "tag=" UUID
  UUID            = 1*( hex | "-" )
  other-param     = ( token | ( token "=" ( token | quoted-string )))
  headers         = "?" header *( "&" header )
  header          = hname "=" hvalue
  hname           = 1*uric
  hvalue          = *uric
  uric            = reserved | unreserved | escaped
  reserved        = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" |
                    "$" | ","
  digits          = 1*DIGIT


   Figure 3: SIP URL syntax
```

**Comment by eric-brechemier** [comment]
Both parameters can be included in this way:

```
<Sip>sip:jack@example.com;transport=tls;secure=true</Sip>
```

The previous form resulted in invalid parameter values:

```
transport: tls&secure=true
```

or

```
secure: true&transport=tls
```

**Comment by eric-brechemier** [comment]
I updated the [description of Linphone client setup](https://github.com/eric-brechemier/how-i-replaced-skype-with-twilio/issues/5#issuecomment-488824107), adding the possibility to make encryption of inbound calls required.

## Connect to SIP from your Computer
(…)

3. I also chose to make encryption mandatory. This check applies to incoming calls. When this check is enabled, incoming calls will get rejected unless they are encrypted as well. Leaving the check disabled allows to receive incoming calls even if they were sent encrypted. We will configure our bridge to always encrypt incoming calls, so it's up to you.

<p align="center">
  <kbd>
    <img width="253" alt="Encryption is not mandatory" src="https://user-images.githubusercontent.com/151276/154818815-029fa444-1561-4537-b094-1db79bc19747.png">
  </kbd>
</p>

<p align="center">
  <kbd>
    <img width="250" alt="Encryption is mandatory" src="https://user-images.githubusercontent.com/151276/154818512-afccf911-4baf-4f18-a38e-7803880e09fd.png">
  </kbd>
</p>

**Comment by eric-brechemier** [comment]
I also updated the description of the steps to [configure the TwiML Bin script](https://github.com/eric-brechemier/how-i-replaced-skype-with-twilio/issues/5#issuecomment-491344662) _Receiving Phone Calls from Regular Phones to SIP_:

## Receiving Calls
(…)

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Dial>
    <Sip>sip:me@1-202-555-0162.sip.us1.twilio.com;transport=tls;secure=true</Sip>
  </Dial>
</Response>
```
(…)
<p align="center">
  <kbd>
    <img width="400" alt="New TwiML Bin Receiving Calls from Regular Phones to SIP" src="https://user-images.githubusercontent.com/151276/154819078-37b1d05c-6ada-4174-ac01-75e41728256b.png">
  </kbd>
</p>

**Comment by eric-brechemier** [comment]
@AmIJesse Thanks! Starting from your input, I have finally made the changes to successfully encrypt phone calls.
